# -*- coding: utf-8 -*-
"""W3_DAY-5-RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLUH-MQykx2ysAMHrFbxpfSj5SKBERR6

CODE OF RNN
"""

# import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler

from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score
)

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import (
    SimpleRNN, Dense
)

print("Libraries Imported successfully!")

#load airline  passengers dataset

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv"

df = pd.read_csv(url)

print("Showing 5 rows: ")
print(df.head())
print()
print("Showing shape of the dataset: ")
print(df.shape)

# passenger trend

plt.figure(
    figsize=(14,5)
)

plt.plot(
    df['Passengers'],
    linewidth = 3
)
plt.title("Airline Passenger Trend")
plt.xlabel("Months")
plt.ylabel("Passengers")

plt.grid(True)
plt.show()

# normalisation

data = df['Passengers'].values

data=data.reshape(-1,1)

scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)
print(data_scaled[:5])

def create_sequences(
    dataset,
    time_step=12
):
    X=[]
    y=[]
    for i in range(
        len(dataset)-time_step
    ):
        X.append(
            dataset[
                i:(i+time_step),
                0
            ]
        )
        y.append(
            dataset[
                i+time_step,
                0
            ]
        )
    return np.array(X), np.array(y)
X,y=create_sequences(data_scaled,12)
print(X.shape)
print(y.shape)

# train test split

split = int(len(X) * 0.8)

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

print("X Train Shape: ", X_train.shape)
print("X Test Shape:" ,X_test.shape)

print("y Train Shape:", y_train.shape)
print("y Test Shape:" , y_test.shape)

# rnn input shape

X_train = X_train.reshape(
    X_train.shape[0],
    X_train.shape[1],
    1
)

X_test = X_test.reshape(
    X_test.shape[0],
    X_test.shape[1],
    1
)

print(X_train.shape)

#simple rnn model

model = Sequential()

model.add(
    SimpleRNN(
        units= 50,
        activation = "tanh",
        input_shape = (12,1)
    )
)

model.add(
    Dense(
        1
    )
)

model.summary()

# compile model

model.compile(
    optimizer= "adam",
    loss="mse"
)

# train model

history = model.fit(
    X_train,
    y_train,
    epochs = 100,
    batch_size = 8,
    validation_data = (
        X_test,
        y_test
    )
)